#  Template publish .NET Core package to nuget.org

#  This template allows you to publish your .NET Core package to nuget.org.
#  The workflow allows running tests, code linting and security scans on feature branches (as well as master).
#  The .NET Core package will be validated and published after the code is merged to master.

# Prerequisites: $NUGET_SECRET_API_KEY setup as deployment variables.

# To run your pipeline on a Windows machine, create a self-hosted Windows runner.
# For instructions on setting up a Windows runner, see https://support.atlassian.com/bitbucket-cloud/docs/set-up-runners-for-windows/

image: mcr.microsoft.com/dotnet/sdk:8.0

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - dotnetcore
        script:
          - dotnet restore
          - dotnet build --configuration Release --no-restore
          - dotnet publish --configuration Release --no-restore --no-build /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$BITBUCKET_CLONE_DIR/artifacts"
          - dotnet test --configuration Release --no-restore --no-build
        artifacts:
          - artifacts/**